disp(' ')
disp('------------------------------------------------')
disp('TJ40 CALCULATION PROGRAM - VERSION 1.00')
disp('              External Version                  ')
disp('------------------------------------------------')
disp(' ')
