

StartAll = [{'ContStartP->FuelHighPulse'}, {'_FUEL_HIGH_PULSE'};...
{'ContStartP->FuelImpulseTime'}, {'_FUEL_IMPULSE_TIME'};...
{'ContStartP->FuelInit'}, {'_FUEL_INIT'};...
{'ContStartP->FuelPerc'}, {'_FUEL_PERC'};...
{'ContStartP->FuelRamp'}, {'_FUEL_RAMP'};...
{'ContStartP->POilAlarm'}, {'_POIL_ALARM'};...
{'ContStartP->POilShutDown'}, {'_POIL_SHUTDOWN'};...
{'ContStartP->RPMIdle'}, {'_RPM_IDLE'};...
{'ContStartP->RPMIgnOff'}, {'_RPM_IGN_OFF'};...
{'ContStartP->RPMRelaysOn'}, {'_RPM_RELAYS_ON'};...
{'ContStartP->RPMValve100'}, {'_RPM_VALVE_100'};...
{'ContStartP->TimeAccomodation'}, {'_TIME_ACCOMODATION'};...
{'ContStartP->TimeIgnition'}, {'_TIME_IGNITION'};...
{'ContStartP->TimeLowPOil'}, {'_TIME_LOW_POIL'};...
{'ContStartP->TimeOvertemp'}, {'_TIME_OVERTEMP'};...
{'ContStartP->Tt5AvFlameOn'}, {'_Tt5AV_FLAME_ON'};...
{'ContStartP->Tt5AvMax'}, {'_Tt5AV_MAX'};...
{'ContStartP->ValveInit'}, {'_VALVE_INIT'};...
{'ContStartP->ValveTotal'}, {'_VALVE_TOTAL'};...
{'ContStartP->WaitAction'}, {'_WAIT_ACTION'}];

% %Adds electric motor start parameters
% StartAll = [StartAll; {'ContStartP->StrtInit'},{'_STRTINIT'};... 
%     {'ContStartP->StrtMax'},{'_STRTMAX'};... 
%     {'ContStartP->StrtRampCoef'},{'_STRTRAMPCOEF'};... 
%     {'ContStartP->StrtRPMOff'},{'_STRTRPMOFF'};... 
%     {'ContStartP->StrtWhich'},{'_STRTWHICH'}];