
		EngConstAll = [{'EngPars->Fuel_BOut'}, {'_FUEL_BOUT'};...
		{'EngPars->Ign_Delta'}, {'_IGN_DELTAT'};...
		{'EngPars->Ign_Time'}, {'_IGN_TIME'};...
		{'EngPars->POilMin'}, {'_POIL'};...
		{'EngPars->Valve_Fuel'}, {'_VALVE_FUEL'};...
		{'EngPars->Ath'}, {'_Ath_NOZZLE'};...
		{'EngPars->NDes'}, {'_NDES'};...
		{'EngPars->RPM_BOut'}, {'_RPM_BOUT'};...
		{'*WfMax_Pump'}, {'_WFMAX'};...
        {'EngPars->TCSCV'}, {'_TCSCV'};...
        {'EngPars->TCSCG'}, {'_TCSCG'};...
        {'EngPars->TCOPEN'}, {'_TCOPEN'};...
        {'EngPars->PSSHORT'}, {'_PSSHORT'};... 
		{'EngPars->PFUELSHORT'}, {'_PFUELSHORT'};...
        {'EngPars->PSSOPEN'}, {'_PSSOPEN'};...  
		{'EngPars->Tt4HIGH'}, {'_TT4MAX * 1.15'};...
        {'EngPars->Tt4BLLCK'}, {'_Tt4BLLCK'};... 
        {'EngPars->Tt4SHLCK'}, {'_Tt4SHLCK'};...
		{'EngPars->RPMHIGH'}, {'_NMAX * 1.15'};...
		{'EngPars->RPMSOPEN'}, {'_RPMOPEN'};...
		{'EngPars->RPMSSHORT'}, {'_RPMSHORT'};...
    	{'EngPars->VIBSHORT'}, {'_VIBSHORT'};...
        {'EngPars->VIBOPEN'}, {'_VIBOPEN'};... 
        {'EngPars->VIBHIGH'}, {'_VIBHIGH'};... 
        {'EngPars->POILHIGH'}, {'_POILHIGH'};... 
        {'EngPars->POILLOW'}, {'_POILLOW'};... 
        {'EngPars->PFUELHIGH'}, {'_PFUELHIGH'};...
        {'EngPars->PFUELLOW'}, {'_PFUELLOW'};...
		{'EngPars->TBearHIGH[0]'}, {'_BEAR_TMAX_0 * 1.15'};...
		{'EngPars->TBearHIGH[1]'}, {'_BEAR_TMAX_1 * 1.15'};...
		{'EngPars->TBearHIGH[2]'}, {'_BEAR_TMAX_2 * 1.15'};...
        {'EngPars->PFUELMODEL'}, {'_PFUELMODEL'};...
        {'EngPars->POILMODEL'}, {'_POILMODEL'};...
        {'EngPars->VIBMODEL'}, {'_VIBMODEL'};...
		{'EngPars->TTCTimeConst'}, {'_TTCTIMECONST'};...
		{'EngPars->PSensTimeConst'}, {'_PSENSTIMECONST'};...
		{'EngPars->FuelPumpTimeConstant'}, {'_FUELPUMPTIMECONSTANT'}];