
% %Saves current path
% CurPath = pwd;
% %Goes to main path
% cd ..
%
EngFoldPath = [pwd filesep EngFoldName];

%

%--------------------------------
%GENERATES NEW T-MATS DATA FOLDER
%--------------------------------

%Defines Folder name
TMATSDataFileName = 'TMATSData';
%Defines new name for Alt0dT0.m function - for the case where both the old
%TMATS generation and the new one must work together
NewAlt0dT0FuncName = 'Alt0dT0Mtx';
%Engine data path
EngDataFold = [EngFoldPath filesep TMATSDataFileName];

%---------------------------------------
%SETS DESTINATION FILE FOR MATRICES DATA
%---------------------------------------

EngMtxDataFile = 'TMATSLinMtx';

%----------------
%READS .bin FILES
%----------------

BinFileList = [{'iDes_FAN.bin'},{'iDes_HPC.bin'},{'iDes_HPT.bin'},...
               {'iDes_LPC.bin'},{'iDes_LPT.bin'},{'iDes_Nozzle_Core.bin'},...
               {'iDes_Nozzle_Fan.bin'},...
               {'iDes_Compressor.bin'},{'iDes_Turbine.bin'},{'iDes_Nozzle.bin'}];

%Sets the gains for maps and calculated nozzle areas
for i = 1:length(BinFileList)
    %
    if(isfile([EngDataFold filesep char(BinFileList(i))]) > 0)
        %
        fid = fopen([EngDataFold filesep char(BinFileList(i))]);
        FileLines = ReadLines(fid);
        %Verifies which component is being read
        IL = find(char(BinFileList(i)) == '_') + 1;
        IH = find(char(BinFileList(i)) == '.') - 1;
        %
        AuxChar = char(BinFileList(i));
        CompName = AuxChar(IL:IH);
        GainsName = [CompName '_Gains'];
        %
        word = [GainsName '=zeros(1,length(FileLines));' ];
        eval(word);
        %
        for j = 1:length(FileLines)
            word = [GainsName '(j)=' 'str2double(char(FileLines(j)));'];
            eval(word);
        end
    end
end

%-------------------
%DEFINES MAPS VALUES
%-------------------

%Loads MWS and DesPoint data
load([EngDataFold filesep 'MWS']);
load([EngDataFold filesep 'DesPoint']);

if SSFan <= 1
    NDes = DesPoint.NMechDes;
else
    NDes = DesPoint.NMechDesLPT;
end

MWSFields = fieldnames(MWS);

%FAN MAP

FANMapNames = [{'FAN'},{'LPC'},{'HPC'},{'Compressor'},{'4'}];
CompNames = FANMapNames;
MapSet

%LPC MAP

LPCMapNames = [{'LPC'},{'HPC'},{'Compressor'},{'4'}];
CompNames = LPCMapNames;
MapSet

%HPC MAP

HPCMapNames = [{'HPC'},{'Compressor'},{'4'}];
CompNames = HPCMapNames;
MapSet

%HPT MAP

HPTMapNames = [{'HPT'},{'Turbine'},{'4'}];
CompNames = HPTMapNames;
MapSet

%LPT MAP

LPTMapNames = [{'LPT'},{'HPT'},{'Turbine'},{'4'}];
CompNames = LPTMapNames;
MapSet

%Core Nozzle
NozzCNames = [{'Nozzle_Core'},{'Nozzle'},{'2'}];
CompNames = NozzCNames;
MapSet

%Fan Nozzle
NozzFNames = [{'Nozzle_Fan'},{'Nozzle'},{'2'}];
CompNames = NozzFNames;
MapSet

% if exist('MWS','var')
%     %
%     
% end

%---------------------------------
%SAVES MAPS AND LINEARIZATION DATA
%---------------------------------

% %Saves MWS data (maps data)
% cd(TMATSDataFileName);
% if exist('MWS','var')
% %     save MWS.mat MWS
% end
% cd ..

%Saves linearization data
Alt0dT0Names = [{'Alt0dT0.txt'},{'Alt0dT0.m'}];
% for i = 1:length(Alt0dT0Names)
%     if isfile([EngDataFold filesep char(Alt0dT0Names(i))])
%         %Sets word for opening file and evals expression
%         word = ['fid=fopen(''' EngDataFold filesep char(Alt0dT0Names(i)) ''');'];
%         eval(word);
%         %Copies lines from file
%         Alt0dT0Lines = ReadLines(fid);
%         %Closes file
%         fclose(fid);
%         %Opens destination file
%         fid = fopen([EngFoldPath filesep EngMtxDataFile '.m'],'w');
%         %Writes the linearization data on file
%         WriteLines(Alt0dT0Lines,fid);
%         %Closes file
%         fclose(fid);        
%     end
% end

%Initially, indicates that SetLinPars must be called
CallSetLinPars = 1;
CallSetLinMtx = 0;

%Verifies if a .txt file has been automatically generated by TMATS
if isfile([EngDataFold filesep char(Alt0dT0Names(1))])
    %Sets word for opening file and evals expression
    word = ['fid=fopen(''' EngDataFold filesep char(Alt0dT0Names(1)) ''');'];
    eval(word);
    %Copies lines from file
    Alt0dT0Lines = ReadLines(fid);
    %Closes file
    fclose(fid);
    %Opens destination file
    fid = fopen([EngFoldPath filesep EngMtxDataFile '.m'],'w');
    %Writes the linearization data on file
    WriteLines(Alt0dT0Lines,fid);
    %Closes file
    fclose(fid);
end

%Verifies if a .m file has been automatically generated by TMATS
if isfile([EngDataFold filesep char(Alt0dT0Names(2))])
    %Sets word for opening file and evals expression
    word = ['fid=fopen(''' EngDataFold filesep char(Alt0dT0Names(2)) ''');'];
    eval(word);
    %Copies lines from file
    Alt0dT0Lines = ReadLines(fid);
    %Closes file
    fclose(fid);
    %
    [row,col] = size(Alt0dT0Lines);
    %Searches for the line where the word '=' is present
    for i = 1:row
        %Defines AuxChar as the i-th line of Alt0dT0Lines
        AuxChar = char(Alt0dT0Lines(i));
        %Finds the indexes for the word '['
        Indexes = find(ismember(char(Alt0dT0Lines(i)),'='));
        %Verifies if any indexes have been found
        if ~isempty(Indexes)
            %             IL = i;
            %Gets the index where the character is ']''
            IHChar = Indexes(1);
            %             %Replaces ']' for ' '
            %             AuxChar(ILChar) = ' ';
            if ~isempty(NewAlt0dT0FuncName)
                %Corrects AuxChar
                AuxChar = [AuxChar(1:IHChar) ' ' NewAlt0dT0FuncName];
                %Corrects first line of Alt0dT0Lines
                Alt0dT0Lines(i) = cellstr(AuxChar);
                %Creates file with new name if it differs from original
                %name and copies the content of original function
                if ~strcmp(NewAlt0dT0FuncName,'Alt0dT0')
                    %Deletes previously created file if it already exists
                    if isfile(['LinPars' filesep NewAlt0dT0FuncName '.m'])
                        delete(['LinPars' filesep NewAlt0dT0FuncName '.m']);
                    end
                    %Creates new file
                    fid = fopen(['LinPars' filesep NewAlt0dT0FuncName '.m'],'w');
                    %Write the lines in the new file
                    WriteLines(Alt0dT0Lines,fid);
                    %Closes files
                    fclose(fid);
                end
            end
            break;
        end
    end
    %Searches for the line where the word '[' is present
    for i = 1:row
        %Defines AuxChar as the i-th line of Alt0dT0Lines
        AuxChar = char(Alt0dT0Lines(i));
        %Finds the indexes for the word '['
        Indexes = find(ismember(char(Alt0dT0Lines(i)),'['));
        %Verifies if any indexes have been found
        if ~isempty(Indexes)
            IL = i;
            %Gets the index where the character is ']''
            ILChar = Indexes(1);
%             %Replaces ']' for ' '
%             AuxChar(ILChar) = ' ';
            %Corrects AuxChar
            AuxChar = AuxChar(ILChar:end);
            %Corrects first line of Alt0dT0Lines
            Alt0dT0Lines(i) = cellstr(AuxChar);
            break;
        end            
    end
    %Searches for the line where the word ']' is present
    for i = 1:row
        %Defines AuxChar as the i-th line of Alt0dT0Lines
        AuxChar = char(Alt0dT0Lines(i));
        %Finds the indexes for the word 'function'
        Indexes = find(ismember(char(Alt0dT0Lines(i)),']'));
        %Verifies if any indexes have been found
        if ~isempty(Indexes)
            IH = i;
            %Corrects AuxChar for excluding the word 'function'
            IHChar = Indexes(1);
%             %Replaces ']' for ','
%             AuxChar(IHChar) = ',';
            %Corrects AuxChar
            AuxChar = AuxChar(1:IHChar);
            %Corrects first line of Alt0dT0Lines
            Alt0dT0Lines(i) = cellstr(AuxChar);
            break;
        end
    end
    %Gets the lines of interest in Alt0dT0Lines
    Alt0dT0Lines = Alt0dT0Lines(IL:IH);   
    %Corrects Alt0dT0 lines for correct direct call of Alt0dT0.m
    [Alt0dT0Lines,Alt0dT0Vars] = Alt0dT0OutNames(Alt0dT0Lines,NewAlt0dT0FuncName);
    %Deletes previously created file if it already exists
    if isfile(['LinPars' filesep 'DirAlt0dT0Call.m'])
        delete(['LinPars' filesep 'DirAlt0dT0Call.m']);
    end
    %Creates file for calling the new generated function directly
    fid = fopen(['LinPars' filesep 'DirAlt0dT0Call.m'],'w');
    %Write the lines in the new file
    WriteLines(Alt0dT0Lines,fid);
    %Closes files
    fclose(fid);
    %Indicates that SetLinMtx must be called and not SetLinPars
    CallSetLinPars = 0;
    CallSetLinMtx = 1;
end

