
%--------------------------------
%CALCULATION OF SUB-IDLE MATRICES
%--------------------------------

switch SubIdleModel
    
    case 1
        
        %Calculates cold sub-idle (windmill) matrices
        [AwmMtx,BwmMtx,CwmMtx,DwmMtx,RPMwmMtx,WfwmMtx,...
            Pt21wmMtx,Pt21CwmMtx,Pt21DwmMtx,...
            Pt3wmMtx,Pt3CwmMtx,Pt3DwmMtx,...
            Pt5wmMtx,Pt5CwmMtx,Pt5DwmMtx,...
            Pt6wmMtx,Pt6CwmMtx,Pt6DwmMtx,...
            Tt21wmMtx,Tt21CwmMtx,Tt21DwmMtx,...
            Tt3wmMtx,Tt3CwmMtx,Tt3DwmMtx,...
            Tt4wmMtx,Tt4CwmMtx,Tt4DwmMtx,...
            Tt5wmMtx,Tt5CwmMtx,Tt5DwmMtx,...
            Tt6wmMtx,Tt6CwmMtx,Tt6DwmMtx] = WindMillCalc(MNLinVec);
        
        %Calculate hot sub-idle (with combustion) matrices
        [AshMtx,BshMtx,Pt3CshMtx,Pt3DshMtx,Tt4CshMtx,Tt4DshMtx,...
            NcFANshMtx,WfshMtx,Tt4shMtx,Pt3shMtx,RPMshMtx,...
            Pt21shMtx,Pt21CshMtx,Pt21DshMtx,...
            Pt5shMtx,Pt5CshMtx,Pt5DshMtx,...
            Pt6shMtx,Pt6CshMtx,Pt6DshMtx,...
            Tt21shMtx,Tt21CshMtx,Tt21DshMtx,...
            Tt3shMtx,Tt3CshMtx,Tt3DshMtx,...
            Tt5shMtx,Tt5CshMtx,Tt5DshMtx,...
            Tt6shMtx,Tt6CshMtx,Tt6DshMtx] = SubIdleHotCalc;
        
    case 2
        
        %Calculates cold sub-idle (windmill matrices)
        [AwmMtx,BwmMtx,CwmMtx,DwmMtx,RPMwmMtx,WfwmMtx,...
            Pt21wmMtx,Pt21CwmMtx,Pt21DwmMtx,...
            Pt3wmMtx,Pt3CwmMtx,Pt3DwmMtx,...
            Pt5wmMtx,Pt5CwmMtx,Pt5DwmMtx,...
            Pt6wmMtx,Pt6CwmMtx,Pt6DwmMtx,...
            Tt21wmMtx,Tt21CwmMtx,Tt21DwmMtx,...
            Tt3wmMtx,Tt3CwmMtx,Tt3DwmMtx,...
            Tt4wmMtx,Tt4CwmMtx,Tt4DwmMtx,...
            Tt5wmMtx,Tt5CwmMtx,Tt5DwmMtx,...
            Tt6wmMtx,Tt6CwmMtx,Tt6DwmMtx] = WindMillMtxLoad(EngFoldName,UpperFolder);
        
        %Calculates hot sub-idle (with combustion) matrices
        [AshMtx,BshMtx,Pt3CshMtx,Pt3DshMtx,Tt4CshMtx,Tt4DshMtx,...
            NcFANshMtx,WfshMtx,Tt4shMtx,Pt3shMtx,RPMshMtx,...
            Pt21shMtx,Pt21CshMtx,Pt21DshMtx,...
            Pt5shMtx,Pt5CshMtx,Pt5DshMtx,...
            Pt6shMtx,Pt6CshMtx,Pt6DshMtx,...
            Tt21shMtx,Tt21CshMtx,Tt21DshMtx,...
            Tt3shMtx,Tt3CshMtx,Tt3DshMtx,...
            Tt5shMtx,Tt5CshMtx,Tt5DshMtx,...
            Tt6shMtx,Tt6CshMtx,Tt6DshMtx] = SubIdleMtxLoad(EngFoldName,UpperFolder);
        
        %Calculates PI gains for sub-idle region
        if getPIshGains == 1
            PICalcSubIdle
        end
                
end