    
mex -g NOT_USED\TJ1200\Research\FADEC\PIMMRF\PIMMRF_TJ1200_MainLoop.c...
        -g NOT_USED\TJ1200\Research\FADEC\PIMMRF\StartingFunctions.c...
        -g NOT_USED\TJ1200\Research\FADEC\PIMMRF\ControlFunctions.c...
        -g NOT_USED\TJ1200\Research\FADEC\PIMMRF\PIMinMaxTJ1200.c...
        -g NOT_USED\TJ1200\Research\FADEC\PIMMRF\getTJ1200StartPars.c...
        -g NOT_USED\TJ1200\Research\FADEC\PIMMRF\getTJ1200N_KpMtx.c...
        -g NOT_USED\TJ1200\Research\FADEC\PIMMRF\getTJ1200N_KiMtx.c...
        -g NOT_USED\TJ1200\Research\FADEC\PIMMRF\getTJ1200FNperContMtx.c...
        -g NOT_USED\TJ1200\Research\FADEC\PIMMRF\getTJ1200NcFANContMtx.c...
        -g NOT_USED\TJ1200\Research\FADEC\PIMMRF\MtxIntFunctions.c
    
    %Hardware version - Test Bench 
    
    mex -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\PIMMRF_TJ1200_TestBench.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\StartingFunctions.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\ControlFunctions.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\ShutDownFunctions.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\FailSafeFunctions.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\TCFault.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\PIMinMaxRF.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\PIOil.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200AMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200AltLinVec.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200ASVec.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200BMtx.c... 
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200ContConst.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200DSVec.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200PRHPCMapMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200Pt3Mtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200Pt3DMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200Pt5Mtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200Pt5DMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200Tt4Mtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200Tt4DMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200Tt5Mtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200Tt5DMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200Ts0Mtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200DeltaMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200MNLinVec.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200NcHPCMapMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200NcVec.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200N_KpMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200N_KiMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200FNcMaxContMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200FNperContMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200NcFANContMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200WcHPCMapMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\getTJ1200WfMtx.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\MtxIntFunctions.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\Ambient_TMATS.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\functions_TMATS.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\interp1AC_TMATS.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\interp2AC_TMATS.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\PeripheralDyn.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\PcalcStat_TMATS.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\pt2sc_TMATS.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\sp2tc_TMATS.c...
        -g NOT_USED\TJ1200\TestBench\FADEC\PIMMRF\t2hc_TMATS.c
               
    %TF1200 ENGINE
    
    mex -g NOT_USED\TF1200\FADEC\PIMMRF\PIMMRF_TF1200_MainLoop.c...
        -g NOT_USED\TF1200\FADEC\PIMMRF\StartingFunctions.c...
        -g NOT_USED\TF1200\FADEC\PIMMRF\ControlFunctions.c...
        -g NOT_USED\TF1200\FADEC\PIMMRF\PIMinMaxTF1200.c...
        -g NOT_USED\TF1200\FADEC\PIMMRF\getTF1200StartPars.c...
        -g NOT_USED\TF1200\FADEC\PIMMRF\getTF1200N_KpMtx.c...
        -g NOT_USED\TF1200\FADEC\PIMMRF\getTF1200N_KiMtx.c...
        -g NOT_USED\TF1200\FADEC\PIMMRF\getTF1200FNperContMtx.c...
        -g NOT_USED\TF1200\FADEC\PIMMRF\getTF1200NcFANContMtx.c...
        -g NOT_USED\TF1200\FADEC\PIMMRF\MtxIntFunctions.c
        
    %GE J85 ENGINE
    
    mex -g NOT_USED\GEJ85\FADEC\PIMMRF\PIMMRF_GEJ85_MainLoop.c...
        -g NOT_USED\GEJ85\FADEC\PIMMRF\StartingFunctions.c...
        -g NOT_USED\GEJ85\FADEC\PIMMRF\ControlFunctions.c...
        -g NOT_USED\GEJ85\FADEC\PIMMRF\PIMinMaxGEJ85.c...
        -g NOT_USED\GEJ85\FADEC\PIMMRF\getGEJ85StartPars.c...
        -g NOT_USED\GEJ85\FADEC\PIMMRF\getGEJ85N_KpMtx.c...
        -g NOT_USED\GEJ85\FADEC\PIMMRF\getGEJ85N_KiMtx.c...
        -g NOT_USED\GEJ85\FADEC\PIMMRF\getGEJ85FNperContMtx.c...
        -g NOT_USED\GEJ85\FADEC\PIMMRF\getGEJ85NcFANContMtx.c...
        -g NOT_USED\GEJ85\FADEC\PIMMRF\getGEJ85Ps3MinMtx.c...
        -g NOT_USED\GEJ85\FADEC\PIMMRF\MtxIntFunctions.c
    
    mex -g NOT_USED\GEJ85\FADEC\PIMMA\PIMMA_GEJ85_MainLoop.c...
        -g NOT_USED\GEJ85\FADEC\PIMMA\StartingFunctions.c...
        -g NOT_USED\GEJ85\FADEC\PIMMA\ControlFunctions.c...
        -g NOT_USED\GEJ85\FADEC\PIMMA\PIMinMaxAccGEJ85.c...
        -g NOT_USED\GEJ85\FADEC\PIMMA\getGEJ85StartPars.c...
        -g NOT_USED\GEJ85\FADEC\PIMMA\getGEJ85N_KpMtx.c...
        -g NOT_USED\GEJ85\FADEC\PIMMA\getGEJ85N_KiMtx.c...
        -g NOT_USED\GEJ85\FADEC\PIMMA\getGEJ85FNperContMtx.c...
        -g NOT_USED\GEJ85\FADEC\PIMMA\getGEJ85NcFANContMtx.c...
        -g NOT_USED\GEJ85\FADEC\PIMMA\MtxIntFunctions.c
    
    
    mex -g NOT_USED\GEJ85\FADEC\QSMCMMRF\QSMC_GEJ85_MainLoop.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\StartingFunctions.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\ControlFunctions.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\QSMCFunctions.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\QSMCMinMaxGEJ85.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85StartPars.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85DeltaMtx.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85ThetaMtx.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85AMtx.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85BMtx.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85WfMtx.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85Tt5CMtx.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85Tt5DMtx.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85Tt5Mtx.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85FNperContMtx.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\getGEJ85NcFANContMtx.c...
        -g NOT_USED\GEJ85\FADEC\QSMCMMRF\MtxIntFunctions.c