
%Defines dummy matrix
[~,column,~] = size(NcFANMtx);
Dummy = zeros(1,column);
VarsPerLine = 5;

GetFuncMatrices = [{'NcFANContMtx'}, {'N_KpMtx'}, {'N_KiMtx'}, {'FNperContMtx'}, {'FNcMaxContMtx'}, {'NcMtx'}, {'Pt21Mtx'}, {'Pt3Mtx'}, {'Pt5Mtx'}, {'Pt6Mtx'},...
	{'Tt21Mtx'}, {'Tt3Mtx'}, {'Tt4Mtx'}, {'Tt5Mtx'}, {'Tt6Mtx'}, {'WfMtx'}, {'AMtx'}, {'BMtx'}, {'Pt21DMtx'}, {'Pt3DMtx'}, {'Pt5DMtx'}, {'Pt6DMtx'},...
	{'Tt21DMtx'}, {'Tt3DMtx'}, {'Tt4DMtx'}, {'Tt5DMtx'}, {'Tt6DMtx'}, {'NcFANMapMtx'}, {'WcFANMapMtx'}, {'WcFANStallMtx'}, {'PRFANMapMtx'},...
	{'PRFANStallMtx'}, {'EffFANMapMtx'}, {'NcHPTMapMtx'}, {'WcHPTMapMtx'}, {'PRHPTMapMtx'}, {'EffHPTMapMtx'},...
	{'NcHPCMapMtx'}, {'WcHPCMapMtx'}, {'WcHPCStallMtx'}, {'PRHPCMapMtx'}, {'PRHPCStallMtx'}, {'EffHPCMapMtx'}, {'MNLinVec'}, {'AltLinVec'}, {'DeltaMtx'}, {'Ts0Mtx'},...
    {'AwmMtx'}, {'AshMtx'}, {'BwmMtx'}, {'BshMtx'}, {'RPMwmMtx'}, {'RPMshMtx'}, {'Tt4CshMtx'}, {'Tt4DshMtx'}, {'Tt4shMtx'}, {'WfshMtx'},...
	{'ASVec'}, {'DSVec'}, {'NcVec'}];

% GetFuncMatrices = [GetFuncMatrices {'NcshFAN'}];

GetFuncConst = cellstr(['void get' EngineName 'ContConst(struct ControllerConstants *ContConst);']);

%Defines all matrices to be printed in code
AllMatrices = [{'Ts0'},{'DeltaMtx'},{'ThetaMtx'},{'AMtx'},{'BMtx'}, ...
    {'Pt21CMtx'}, {'Pt21DMtx'}, {'Tt21CMtx'}, {'Tt21DMtx'}, ...
    {'Pt3CMtx'}, {'Pt3DMtx'}, {'Tt3CMtx'}, {'Tt3DMtx'}, ...
    {'Tt4CMtx'}, {'Tt4DMtx'}, ...
    {'Pt5CMtx'}, {'Pt5DMtx'}, {'Tt5CMtx'}, {'Tt5DMtx'}, ...
    {'Pt6CMtx'}, {'Pt6DMtx'}, {'Tt6CMtx'}, {'Tt6DMtx'}, ...
    {'N_KpMtx'}, {'N_KiMtx'}, {'Pt3_KpMtx'}, {'Pt3_KiMtx'}, ...
    {'Tt4_KpMtx'}, {'Tt4_KiMtx'}, {'Tt5_KpMtx'}, {'Tt5_KiMtx'}, ...
    {'NcFANMtx'}, ...
    {'Pt21Mtx'}, {'Tt21Mtx'}, ...
    {'Pt3Mtx'}, {'Tt3Mtx'}, ...
    {'WfMtx'}, {'Tt4Mtx'}, ...
    {'Pt5Mtx'}, {'Tt5Mtx'}, {'Pt6Mtx'}, {'Tt6Mtx'}, ...
    {'FNMtx'}, {'FNperMtx'}, ...
    {'NcFANMap'}, {'WcFANMap'}, {'EffFANMap'}, {'PRFANMap'}, ...
    {'NcHPCMap'}, {'WcHPCMap'}, {'EffHPCMap'}, {'PRHPCMap'}, ...
    {'NcHPTMap'}, {'WcHPTMap'}, {'EffHPTMap'}, {'PRHPTMap'}, ...
    {'PRFANStall'}, {'WcFANStall'}, {'PRHPCStall'}, {'WcHPCStall'}, ...
    {'FNperContMtx'}, {'FNcMaxContMtx'}, {'NcFANContMtx'}, ...
    {'MNLinVec'}, {'AltLinVec'}, ...
    {'AwmMtx'}, {'BwmMtx'}, {'CwmMtx'}, {'DwmMtx'}, {'RPMwmMtx'}, ...
    {'AshMtx'}, {'BshMtx'}, {'Pt3CshMtx'}, {'Pt3DshMtx'}, {'Tt4CshMtx'}, {'Tt4DshMtx'}, ...
    {'NcFANshMtx'}, {'WfshMtx'}, {'Tt4shMtx'}, {'Pt3shMtx'}, {'RPMshMtx'}, ...
    {'ASVec'}, {'DSVec'}, {'NcVec'}, {'Dummy'}];

%Finds difference between matrices in get functions and the total of
%matrices
DiffMatrices = [];
for i = 1:length(AllMatrices)
    if ~ismember(AllMatrices(i),GetFuncMatrices)
        DiffMatrices = [DiffMatrices AllMatrices(i)];
    end
end

%Defines a vector with the number of different corrected rotation speeds
%used
NcFANMtx_FirstRow = NcFANMtx(1,:);
PRFANMap_FirstRow = PRFANMap(1,:);

%Defines matrices from which element numbers are aquired
% SizeMatrices = [{'AltLinVec'},{'MNLinVec'},{'NcFANMtx_FirstRow'},{'AMtx'},...
%                 {'N_KiMtx'},{'NcFANMap'},{'WcFANMap'},{'NcHPCMap'},...
%                 {'WcHPCMap'},{'NcHPTMap'}, {'WcHPTMap'},{'PRHPTMap'}];

% SizeMsgs = [{'/*Number of altitude points used for gain calculation */'},...
%             {'/* Number of Mach number points used for gains calculation */'},...
%             {'/* Number of different corrected rotation speeds used in linearization */'},...
%             {'/* Number of steady operating points used for linearization at Sea Level */'},...
%             {'/* Number of total steady operating points used for Power Management Controller - all altitudes */'},...
%             {'/* Number of Nc point in Fan map */'},...
%             {'/* Number of Wc points in Fan map */'},...
%             {'/* Number of Nc point in HPC map */'},...
%             {'/* Number of Wc points in HPC map */'},...
%             {'/* Number of Nc points in Fan map */'},...
%             {'/* Number of Wc point in HPC map */'},...
%             {'/* Number of PR points in HPC map */'}];

SizeMatrices = [{'AltLinVec'},{'MNLinVec'},{'NcFANMtx_FirstRow'},{'N_KiMtx'},...
                {'ASVec'},{'NcFANMap'},{'PRFANMap_FirstRow'},{'NcHPTMap'},...
                {'PRHPTMap'}];
            
SizeMsgs = [{'/* Steady Operating Points Elements Numbers */'},...
            {''},{''},{''},{''},...
            {'/* Components Maps Element Numbers */'},...
            {''},{''},{''}];
DividingIndex = [0 0 0 0 0 6 0 0 0];
            
SizeDefines = [{'_ALT_ELEM				       '},...
               {'_MN_ELEM 				       '},...
               {'_FN_ELEM				       '},...
               {'_TOTAL_ELEM			       '},...
               {'_AS_ELEM				       '},...
               {'_FAN_NC                      '},...
               {'_FAN_PR                      '},...
               {'_HPT_NC				       '},...
               {'_HPT_PR				       '}];
                        
%-------------------------------------
%GENERATION OF C CODE FOR ALL MATRICES
%-------------------------------------

%Function name
FuncName = 'CodeGenerator';
%Sorts for alphabetic order
AllMatrices = sort(AllMatrices);
%Word do be used as function inputs
cellsword = [{'AllMatrices'},{'GetFuncMatrices'},{'GetFuncConst'},{'VarsPerLine'},{'EngineName'}];
cellsword = [cellsword AllMatrices];
%Initiates auxiliar word
word = [];

%Loop for generating function callilng with the required arguments
for i = 1:length(cellsword)
    if i == 1
        word = [word FuncName '('];
    end
    if i == length(cellsword)
        word = [word char(cellsword(i)) ');'];
    else
        word = [word char(cellsword(i)) ','];
    end
end

%Executes function for generating C code
eval(word);

%-------------------------------------------
%GENERATION FILE CONTAINING ELEMENTS NUMBERS
%-------------------------------------------

%Function name
FuncName = 'MtxSizes';
%Word do be used as function inputs
cellsword = [{'SizeMsgs'},{'DividingIndex'},{'SizeDefines'},{'GetFuncMatrices'},{'VarsPerLine'},{'EngineName'}];
cellsword = [cellsword SizeMatrices];
%Initiates auxiliar word
word = [];

%Loop for generating function callilng with the required arguments
for i = 1:length(cellsword)
    if i == 1
        word = [word FuncName '('];
    end
    if i == length(cellsword)
        word = [word char(cellsword(i)) ');'];
    else
        word = [word char(cellsword(i)) ','];
    end
end

%Executes function for generating C code
eval(word);
