disp(' ')
disp('------------------------------------------------')
disp('TJ300AR CALCULATION PROGRAM - VERSION 1.00')
disp('              External Version                  ')
disp('------------------------------------------------')
disp(' ')
