[MNLinVec, AMtx, BMtx, CMtx, DMtx, ...
N_KpMtx, N_KiMtx, Pt3_KpMtx, Pt3_KiMtx, Tt4_KpMtx, Tt4_KiMtx, Tt5_KpMtx, Tt5_KiMtx, ...
NMtx, Pt3Mtx, Tt4Mtx, Tt5Mtx, EPRMtx, FNMtx, NcMtx, NcFANMtx, NcHPCMtx, WfMtx, Tt3Mtx, Pt5Mtx, FNperMtx, ...
NCMtx, NDMtx, Pt3CMtx, Pt3DMtx, Tt3CMtx, Tt3DMtx, Tt4CMtx, Tt4DMtx, Pt5CMtx, Pt5DMtx, Tt5CMtx, Tt5DMtx] = Alt0dT0Mtx;
