

%Tries to find FNperMtx
if ismember({'FNperMtx'},Alt0dT0Vars)
    %Reads column size of FNperMtx
    [~,col] = size(FNperMtx);
    %Initiates flag indicating flip must be accomplished
    MustFlip = 0;
    %Identifies if FNperMtx is flipped
    if FNperMtx(1,col) < FNperMtx(1,1)
        MustFlip = 1;
    end
end

%Performs matrix flipping
if MustFlip == 1
    %Loop for flipping all variables generated by Alt0dT0
    for i = 1:length(Alt0dT0Vars)
        %Generates word to be evaluated
        word = [char(Alt0dT0Vars(i)) '=fliplr(' char(Alt0dT0Vars(i)) ');'];
        %Evaluates word
        eval(word);
    end
end


% %Reads number of columns of FNper matrix
% [~,col] = size(FNper);
% 
% %Verifies if the last element in the first line is larger than the first
% %one
% %Corrects vector order if thrust vector is backwards
% % if FNper(1,lin) < FNper(1,1)
% if FNper(1,col) < FNper(1,1)
%     
%     %STATE-SPACE MATRICES
%     
%     A  =  fliplr(A);
%     B  =  fliplr(B);
%     C  =  fliplr(C);
%     D  =  fliplr(D);
%     
%     %CONTROLLER GAINS
%     
%     N_Kp  =  fliplr(N_Kp);
%     N_Ki  =  fliplr(N_Ki);
%     Pt3_Kp  =  fliplr(Pt3_Kp);
%     Pt3_Ki  =  fliplr(Pt3_Ki);
%     Tt4_Kp  =  fliplr(Tt4_Kp);
%     Tt4_Ki  =  fliplr(Tt4_Ki);
%     Tt5_Kp  =  fliplr(Tt5_Kp);
%     Tt5_Ki  =  fliplr(Tt5_Ki);
%     
%     %CORRECTED ROTATION SPEEDS
%     
%     NcFAN  =  fliplr(NcFAN);
%     
%     %STATIC VALUES
%     
%     Pt21  =  fliplr(Pt21);
%     Tt21  =  fliplr(Tt21);
%     Pt3   =  fliplr(Pt3);
%     Tt3   = fliplr(Tt3);
%     Tt4   =  fliplr(Tt4);
%     Pt5   =  fliplr(Pt5);
%     Tt5   = fliplr(Tt5);
%     Pt6   =  fliplr(Pt6);
%     Tt6   = fliplr(Tt6);
%     FN    =  fliplr(FN);
%     FNper =  fliplr(FNper);
%     Wf = fliplr(Wf);
%     
%     %     %For the unified model, in a single spool jet, station 21 equals station 3
%     %     %and station 6 equals station 5
%     %     Pt21 = Pt3;
%     %     Tt21 = Tt3;
%     %     Pt6 = Pt5;
%     %     Tt6 = Tt5;
%     
% end