
%--------------------------
%LOADING OF ENGINE MATRICES
%--------------------------

%INITIALIZES ENGINE MATRICES WITH EMPTY VALUES

%State-Space Matrices
ALRMtx = []; BLRMtx = []; CLRMtx = []; DLRMtx = []; 
%Controller Gains
N_KpLRMtx = []; N_KiLRMtx = []; Pt3_KpLRMtx = []; Pt3_KiLRMtx = []; 
Tt4_KpLRMtx = []; Tt4_KiLRMtx = []; Tt5_KpLRMtx = []; Tt5_KiLRMtx = []; 
%Mechanical Rotation Speed
NcFANLRMtx = [];
%Station 2
ThetaLRMtx = []; DeltaLRMtx = [];
%Station 21
Pt21LRMtx = []; Tt21LRMtx = []; 
%Station 3
Pt3LRMtx = []; Tt3LRMtx = []; 
%Station 4
WfLRMtx = []; Tt4LRMtx = [];
%Station 5
Pt5LRMtx = []; Tt5LRMtx = []; 
%Station 6
Pt6LRMtx = []; Tt6LRMtx = []; 
%Station 8
FNLRMtx = []; FNperLRMtx = [];

% %Environment
% MNLinPoints = [];
% AltLinPoints = 0;


%LOADS ENGINE MATRICES

[~,ALRMtx,BLRMtx,CLRMtx,DLRMtx,...
Pt21CLRMtx, Pt21DLRMtx, Tt21CLRMtx, Tt21DLRMtx,...
Pt3CLRMtx, Pt3DLRMtx, Tt3CLRMtx, Tt3DLRMtx,...
Tt4CLRMtx, Tt4DLRMtx,...
Pt5CLRMtx, Pt5DLRMtx, Tt5CLRMtx, Tt5DLRMtx,...
Pt6CLRMtx, Pt6DLRMtx, Tt6CLRMtx, Tt6DLRMtx,...
N_KpLRMtx, N_KiLRMtx, Pt3_KpLRMtx, Pt3_KiLRMtx,... 
Tt4_KpLRMtx, Tt4_KiLRMtx, Tt5_KpLRMtx, Tt5_KiLRMtx,... 
NcFANLRMtx,...
Pt21LRMtx, Tt21LRMtx,...
Pt3LRMtx, Tt3LRMtx,...
WfLRMtx, Tt4LRMtx,...
Pt5LRMtx, Tt5LRMtx, Pt6LRMtx, Tt6LRMtx,... 
FNLRMtx, FNperLRMtx] = SetLinParsLR(0, MNLinPoints,...
ALRMtx,BLRMtx,CLRMtx,DLRMtx,...
N_KpLRMtx, N_KiLRMtx, Pt3_KpLRMtx, Pt3_KiLRMtx,... 
Tt4_KpLRMtx, Tt4_KiLRMtx, Tt5_KpLRMtx, Tt5_KiLRMtx,... 
NcFANLRMtx,...
Pt21LRMtx, Tt21LRMtx,...
Pt3LRMtx, Tt3LRMtx,...
WfLRMtx, Tt4LRMtx,...
Pt5LRMtx, Tt5LRMtx, Pt6LRMtx, Tt6LRMtx,... 
FNLRMtx, FNperLRMtx,SSFan);
