mex -g FADEC_TJ300R.c...
    -g TJ300R\FADEC_get_C\getTJ300RFADECContConst.c...
    -g TJ300R\FADEC_get_C\getTJ300RFADECMtx.c      ...
    -g TJ300R\FADEC_get_C\getTJ300RFADECSizeConst.c...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RAMtx.c          ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RASVec.c         ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RAltLinVec.c     ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RBMtx.c          ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RDSVec.c         ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RDeltaMtx.c      ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RFNcMaxContMtx.c ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RFNperContMtx.c  ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RMNLinVec.c      ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RN_KiMtx.c       ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RN_KishMtx.c     ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RN_KpMtx.c       ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RN_KpshMtx.c     ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RNcFANContMtx.c  ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RNcFANshContMtx.c...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RNcHPCMapMtx.c   ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RNcVec.c         ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RPRHPCMapMtx.c   ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RPt3DMtx.c       ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RPt3Mtx.c        ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RPt5DMtx.c       ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RPt5Mtx.c        ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RTs0Mtx.c        ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RTt4DMtx.c       ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RTt4Mtx.c        ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RTt5DMtx.c       ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RTt5Mtx.c        ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RWcHPCMapMtx.c   ...
    -g TJ300R\FADEC_get_C\Mtx\getTJ300RWfMtx.c         ...
    -g FADEC_Functions_C\Ambient_TMATS.c    ...
    -g FADEC_Functions_C\ControlFunctions.c ...
    -g FADEC_Functions_C\FailSafeFunctions.c...
    -g FADEC_Functions_C\MtxIntFunctions.c  ...
    -g FADEC_Functions_C\PIMinMaxRF.c       ...
    -g FADEC_Functions_C\PIOil.c            ...
    -g FADEC_Functions_C\PcalcStat_TMATS.c  ...
    -g FADEC_Functions_C\PeripheralDyn.c    ...
    -g FADEC_Functions_C\ShutDownFunctions.c...
    -g FADEC_Functions_C\StartingFunctions.c...
    -g FADEC_Functions_C\TCFault.c          ...
    -g FADEC_Functions_C\functions_TMATS.c  ...
    -g FADEC_Functions_C\interp1Ac_TMATS.c  ...
    -g FADEC_Functions_C\interp2Ac_TMATS.c  ...
    -g FADEC_Functions_C\pt2sc_TMATS.c      ...
    -g FADEC_Functions_C\sp2tc_TMATS.c      ...
    -g FADEC_Functions_C\t2hc_TMATS.c
