mex -g FADEC_TG200.c...
    -g TG200\FADEC_get_C\getTG200FADECContConst.c...
    -g TG200\FADEC_get_C\getTG200FADECMtx.c      ...
    -g TG200\FADEC_get_C\getTG200FADECSizeConst.c...
    -g TG200\FADEC_get_C\Mtx\getTG200AMtx.c          ...
    -g TG200\FADEC_get_C\Mtx\getTG200ASVec.c         ...
    -g TG200\FADEC_get_C\Mtx\getTG200AltLinVec.c     ...
    -g TG200\FADEC_get_C\Mtx\getTG200BMtx.c          ...
    -g TG200\FADEC_get_C\Mtx\getTG200DSVec.c         ...
    -g TG200\FADEC_get_C\Mtx\getTG200DeltaMtx.c      ...
    -g TG200\FADEC_get_C\Mtx\getTG200FNcMaxContMtx.c ...
    -g TG200\FADEC_get_C\Mtx\getTG200FNperContMtx.c  ...
    -g TG200\FADEC_get_C\Mtx\getTG200MNLinVec.c      ...
    -g TG200\FADEC_get_C\Mtx\getTG200N_KiMtx.c       ...
    -g TG200\FADEC_get_C\Mtx\getTG200N_KishMtx.c     ...
    -g TG200\FADEC_get_C\Mtx\getTG200N_KpMtx.c       ...
    -g TG200\FADEC_get_C\Mtx\getTG200N_KpshMtx.c     ...
    -g TG200\FADEC_get_C\Mtx\getTG200NcFANContMtx.c  ...
    -g TG200\FADEC_get_C\Mtx\getTG200NcFANshContMtx.c...
    -g TG200\FADEC_get_C\Mtx\getTG200NcHPCMapMtx.c   ...
    -g TG200\FADEC_get_C\Mtx\getTG200NcVec.c         ...
    -g TG200\FADEC_get_C\Mtx\getTG200PRHPCMapMtx.c   ...
    -g TG200\FADEC_get_C\Mtx\getTG200Pt3DMtx.c       ...
    -g TG200\FADEC_get_C\Mtx\getTG200Pt3Mtx.c        ...
    -g TG200\FADEC_get_C\Mtx\getTG200Pt5DMtx.c       ...
    -g TG200\FADEC_get_C\Mtx\getTG200Pt5Mtx.c        ...
    -g TG200\FADEC_get_C\Mtx\getTG200Ts0Mtx.c        ...
    -g TG200\FADEC_get_C\Mtx\getTG200Tt4DMtx.c       ...
    -g TG200\FADEC_get_C\Mtx\getTG200Tt4Mtx.c        ...
    -g TG200\FADEC_get_C\Mtx\getTG200Tt5DMtx.c       ...
    -g TG200\FADEC_get_C\Mtx\getTG200Tt5Mtx.c        ...
    -g TG200\FADEC_get_C\Mtx\getTG200WcHPCMapMtx.c   ...
    -g TG200\FADEC_get_C\Mtx\getTG200WfMtx.c         ...
    -g FADEC_Functions_C\Ambient_TMATS.c    ...
    -g FADEC_Functions_C\ControlFunctions.c ...
    -g FADEC_Functions_C\FailSafeFunctions.c...
    -g FADEC_Functions_C\MtxIntFunctions.c  ...
    -g FADEC_Functions_C\PIMinMaxRF.c       ...
    -g FADEC_Functions_C\PIOil.c            ...
    -g FADEC_Functions_C\PcalcStat_TMATS.c  ...
    -g FADEC_Functions_C\PeripheralDyn.c    ...
    -g FADEC_Functions_C\ShutDownFunctions.c...
    -g FADEC_Functions_C\StartingFunctions.c...
    -g FADEC_Functions_C\TCFault.c          ...
    -g FADEC_Functions_C\functions_TMATS.c  ...
    -g FADEC_Functions_C\interp1Ac_TMATS.c  ...
    -g FADEC_Functions_C\interp2Ac_TMATS.c  ...
    -g FADEC_Functions_C\pt2sc_TMATS.c      ...
    -g FADEC_Functions_C\sp2tc_TMATS.c      ...
    -g FADEC_Functions_C\t2hc_TMATS.c
