
%SUBROUTINE FOR COMPILING A C-SFUNCTION IN ORDER TO DEBUG IT USING VISUAL
%STUDIO WITH MATLAB AS AN ATTACHED PROCESS

%Visual Studio Configuration:
%In Visual Studio, click on Debug/Options and Settings...
%Click on Debugging/Symbols
%In Symbol file (.pdb)locations: Click on the folder icon and add the
%location of the c file to be debugged. Make sure the corresponding box on
%the left side of the folder path is checkmarked
%Check the "Only specified modules" option for only the symbols of interest
%to be loaded by Visula Studio, what is done in a much smaller ammount of
%time than loading all modules
%C:\Users\anton\AppData\Local\Temp\SymbolCache

%Procedure for using Visual Studio 2010:
%1 - Open MATLAB
%2 - Open Visual Studio 2010
%3 - Open "Debug / Attach to Process" in Visual Studio, select MATLAB
%    and click Attach
%4 - Open C-Sfunction C the file to be debugged from Visual Studio 2010
%5 - Set the desired breakpoints
%6 - From MATLAB, run the command mex -g cfilename.c, where cfilename is
%    the name of the file to be debugged
%7 - Run the simulink model. The code execution should stop at the
%    breakpoint that has been set
%Obs 1: Every alteration done in cfilename.c, either from MATLAB or VISUAL
%STUDIO, requires new compilation in order for debugging to work

% if(ismac)
%
%     mex -g MinMaxPICFunc/MMPI_ContLoop.c...
%         -g MinMaxPICFunc/ControlFunctions.c...
%         -g MinMaxPICFunc/getKpNMtx.c...
%         -g MinMaxPICFunc/getKiNMtx.c...
%         -g MinMaxPICFunc/getKpTt4Mtx.c...
%         -g MinMaxPICFunc/getKiTt4Mtx.c...
%         -g MinMaxPICFunc/getRPMMtx.c...
%         -g MinMaxPICFunc/getDummyMtx.c...
%         -g MinMaxPICFunc/getNcMtx.c
%
% end

%         -g SSModelCFunc\TF1200\FADEC_get_C\getTF1200FADECContConst.c...          %TF1200 FADEC Mtx
%         -g SSModelCFunc\TF1200\FADEC_get_C\getTF1200FADECMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200AltLinVec.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200AMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200ASVec.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200BMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200DeltaMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200DSVec.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200FNcMaxContMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200FNperContMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200MNLinVec.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200N_KiMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200N_KpMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200NcFANContMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200NcHPCMapMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200NcVec.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200PRHPCMapMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200Pt3DMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200Pt3Mtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200Pt5DMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200Pt5Mtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200Ts0Mtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200Tt4DMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200Tt4Mtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200Tt5DMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200Tt5Mtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200WcHPCMapMtx.c...
%         -g SSModelCFunc\TF1200\FADEC_get_C\Mtx\getTF1200WfMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\getTF1200HILEngConst.c...                %TF1200 HIL Mtx
%         -g SSModelCFunc\TF1200\HIL_get_C\getTF1200HILMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\getTF1200HILSizeConst.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\getTF1200HILStartPars.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200AshMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200AwmMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200BshMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200BwmMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200EffFANMapMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200EffHPCMapMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200EffHPTMapMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200NcFANMapMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200NcHPTMapMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200NcMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200PRFANMapMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200PRFANStallMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200PRHPCStallMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200PRHPTMapMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Pt21DMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Pt21Mtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Pt6DMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Pt6Mtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200RPMshMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200RPMwmMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Tt21DMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Tt21Mtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Tt3DMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Tt3Mtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Tt4CshMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Tt4DshMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Tt4shMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Tt6DMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200Tt6Mtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200WcFANMapMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200WcFANStallMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200WcHPCStallMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200WcHPTMapMtx.c...
%         -g SSModelCFunc\TF1200\HIL_get_C\Mtx\getTF1200WfshMtx.c...

% -g SSModelCFunc\TJ200\FADEC_get_C\getTJ200FADECContConst.c...          %TJ200 FADEC Mtx
%         -g SSModelCFunc\TJ200\FADEC_get_C\getTJ200FADECMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\getTJ200FADECSizeConst.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200AltLinVec.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200AMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200ASVec.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200BMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200DeltaMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200DSVec.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200FNcMaxContMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200FNperContMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200MNLinVec.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200N_KiMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200N_KpMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200NcFANContMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200NcHPCMapMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200NcVec.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200PRHPCMapMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Pt3DMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Pt3Mtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Pt5DMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Pt5Mtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Ts0Mtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Tt4DMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Tt4Mtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Tt5DMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Tt5Mtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200WcHPCMapMtx.c...
%         -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200WfMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\getTJ200HILEngConst.c...                %TJ200 HIL Mtx
%         -g SSModelCFunc\TJ200\HIL_get_C\getTJ200HILMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\getTJ200HILSizeConst.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\getTJ200HILStartPars.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200AshMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200AwmMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200BshMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200BwmMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200EffFANMapMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200EffHPCMapMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200EffHPTMapMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200NcFANMapMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200NcHPTMapMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200NcMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200PRFANMapMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200PRFANStallMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200PRHPCStallMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200PRHPTMapMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Pt21DMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Pt21Mtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Pt6DMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Pt6Mtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200RPMshMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200RPMwmMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Tt21DMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Tt21Mtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Tt3DMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Tt3Mtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Tt4CshMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Tt4DshMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Tt4shMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Tt6DMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200Tt6Mtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200WcFANMapMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200WcFANStallMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200WcHPCStallMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200WcHPTMapMtx.c...
%         -g SSModelCFunc\TJ200\HIL_get_C\Mtx\getTJ200WfshMtx.c...

Include_NOT_USED = 0;
Include_TJ1200_FuelPump = 1;

if(ispc)
    
    %--------------------
    %ADDS NECESSARY PATHS
    %--------------------
    
    %Adds path containing HIL and FADEC compilatoin code
    
    word = [pwd filesep, 'CompileCall'];
    addpath(word);
    %Verifies if NOT_USED is to be compiled
    if Include_NOT_USED == 1
        word = [pwd filesep, 'NOT_USED' filesep 'CompileCall_NOT_USED'];
        addpath(word);
    end
    %Verifies if TJ1200_FuelPump is to be compiled
    if Include_TJ1200_FuelPump == 1
        word = [pwd filesep, 'TJ1200_FuelPump' filesep 'CompileCall_TJ1200_FuelPump'];
        addpath(word);
    end
    
    %-----------
    %COMPILATION
    %-----------
    
    %Fuel Pump S-Function
    
    %     mex -g TJ1200_FuelPump\FuelPumpCL_TJ1200_TestBench.c...
    %         -g TJ1200_FuelPump\ControlFunctions.c...
    %         -g TJ1200_FuelPump\PIFuelPump.c...
    %         -g TJ1200_FuelPump\MtxIntFunctions.c
    
    if Include_TJ1200_FuelPump == 1
        disp(' ')
        disp('COMPILING TJ1200 FUEL PUMP MODEL')
        disp(' ')
        Compile_TJ1200_FuelPump
    end
    
    %Compiles HIL C code for debugging
    disp(' ')
    disp('COMPILING HIL')
    disp(' ')
    MATLAB_HIL_Compile
    
    %Compiles FADEC C code for debugging
    disp(' ')
    disp('COMPILING FADEC CODES')
    disp(' ')
    MATLAB_FADEC_Compile
    
    %OLDER NOT USED CODE
    if Include_NOT_USED == 1
        disp(' ')
        disp('COMPILING NOT USED CODE')
        disp(' ')
        Compile_NOT_USED
    end
    
    %------------
    %REMOVES PATH
    %------------
    
    %Removes path for TJ1200_FuelPump code
    if Include_TJ1200_FuelPump == 1
        word = [pwd filesep, 'TJ1200_FuelPump' filesep 'CompileCall_TJ1200_FuelPump'];
        addpath(word);
    end
    %Removes path for NOT_USED code
    if Include_NOT_USED == 1
        word = [pwd filesep, 'NOT_USED' filesep 'CompileCall_NOT_USED'];
        rmpath(word);
    end
    word = [pwd filesep, 'CompileCall'];
    rmpath(word);
    
end