
%Defines dummy matrix
[~,column,~] = size(NcFANMtx);
Dummy = zeros(1,column);

%Defines all matrices to be printed in code
AllMatrices = [{'Ts0'},{'DeltaMtx'},{'ThetaMtx'},{'AMtx'},{'BMtx'}, ...
    {'Pt21CMtx'}, {'Pt21DMtx'}, {'Tt21CMtx'}, {'Tt21DMtx'}, ...
    {'Pt3CMtx'}, {'Pt3DMtx'}, {'Tt3CMtx'}, {'Tt3DMtx'}, ...
    {'Tt4CMtx'}, {'Tt4DMtx'}, ...
    {'Pt5CMtx'}, {'Pt5DMtx'}, {'Tt5CMtx'}, {'Tt5DMtx'}, ...
    {'Pt6CMtx'}, {'Pt6DMtx'}, {'Tt6CMtx'}, {'Tt6DMtx'}, ...
    {'N_KpMtx'}, {'N_KiMtx'}, {'Pt3_KpMtx'}, {'Pt3_KiMtx'}, ...
    {'Tt4_KpMtx'}, {'Tt4_KiMtx'}, {'Tt5_KpMtx'}, {'Tt5_KiMtx'}, ...
    {'NcFANMtx'}, ...
    {'Pt21Mtx'}, {'Tt21Mtx'}, ...
    {'Pt3Mtx'}, {'Tt3Mtx'}, ...
    {'WfMtx'}, {'Tt4Mtx'}, ...
    {'Pt5Mtx'}, {'Tt5Mtx'}, {'Pt6Mtx'}, {'Tt6Mtx'}, ...
    {'FNMtx'}, {'FNperMtx'}, ...
    {'NcFANMap'}, {'WcFANMap'}, {'EffFANMap'}, {'PRFANMap'}, ...
    {'NcHPCMap'}, {'WcHPCMap'}, {'EffHPCMap'}, {'PRHPCMap'}, ...
    {'NcHPTMap'}, {'WcHPTMap'}, {'EffHPTMap'}, {'PRHPTMap'}, ...
    {'PRFANStall'}, {'WcFANStall'}, {'PRHPCStall'}, {'WcHPCStall'}, ...
    {'FNperContMtx'}, {'FNcMaxContMtx'}, {'NcFANContMtx'}, ...
    {'MNLinVec'}, {'AltLinVec'}, ...
    {'AwmMtx'}, {'BwmMtx'}, {'CwmMtx'}, {'DwmMtx'}, {'RPMwmMtx'}, ...
    {'AshMtx'}, {'BshMtx'}, {'Pt3CshMtx'}, {'Pt3DshMtx'}, {'Tt4CshMtx'}, {'Tt4DshMtx'}, ...
    {'NcFANshMtx'}, {'WfshMtx'}, {'Tt4shMtx'}, {'Pt3shMtx'}, {'RPMshMtx'}, ...
    {'ASVec'}, {'DSVec'}, {'NcVec'}, {'Dummy'}];

%Function name
FuncName = 'CodeGenerator';

%Sorts for alphabetic order
AllMatrices = sort(AllMatrices);

%Word do be used as function inputs
cellsword = [{'AllMatrices'},{'EngineName'}];
cellsword = [cellsword AllMatrices];

word = [];

%Changes cells into characters
for i = 1:length(cellsword)
    if i == 1
        word = [word FuncName '('];
    end
    if i == length(cellsword)
        word = [word char(cellsword(i)) ');'];
    else
        word = [word char(cellsword(i)) ','];
    end
end

eval(word);

