mex -g SSModelCFunc\FADEC_TJ200.c...
    -g SSModelCFunc\TJ200\FADEC_get_C\getTJ200FADECContConst.c...
    -g SSModelCFunc\TJ200\FADEC_get_C\getTJ200FADECMtx.c      ...
    -g SSModelCFunc\TJ200\FADEC_get_C\getTJ200FADECSizeConst.c...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200AMtx.c          ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200ASVec.c         ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200AltLinVec.c     ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200BMtx.c          ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200DSVec.c         ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200DeltaMtx.c      ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200FNcMaxContMtx.c ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200FNperContMtx.c  ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200MNLinVec.c      ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200N_KiMtx.c       ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200N_KishMtx.c     ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200N_KpMtx.c       ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200N_KpshMtx.c     ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200NcFANContMtx.c  ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200NcFANshContMtx.c...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200NcHPCMapMtx.c   ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200NcVec.c         ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200PRHPCMapMtx.c   ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Pt3DMtx.c       ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Pt3Mtx.c        ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Pt5DMtx.c       ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Pt5Mtx.c        ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Ts0Mtx.c        ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Tt4DMtx.c       ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Tt4Mtx.c        ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Tt5DMtx.c       ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200Tt5Mtx.c        ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200WcHPCMapMtx.c   ...
    -g SSModelCFunc\TJ200\FADEC_get_C\Mtx\getTJ200WfMtx.c         ...
    -g SSModelCFunc\FADEC_Functions_C\Ambient_TMATS.c    ...
    -g SSModelCFunc\FADEC_Functions_C\ControlFunctions.c ...
    -g SSModelCFunc\FADEC_Functions_C\FailSafeFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\MtxIntFunctions.c  ...
    -g SSModelCFunc\FADEC_Functions_C\PIMinMaxRF.c       ...
    -g SSModelCFunc\FADEC_Functions_C\PIOil.c            ...
    -g SSModelCFunc\FADEC_Functions_C\PcalcStat_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\PeripheralDyn.c    ...
    -g SSModelCFunc\FADEC_Functions_C\ShutDownFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\StartingFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\TCFault.c          ...
    -g SSModelCFunc\FADEC_Functions_C\functions_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\interp1Ac_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\interp2Ac_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\pt2sc_TMATS.c      ...
    -g SSModelCFunc\FADEC_Functions_C\sp2tc_TMATS.c      ...
    -g SSModelCFunc\FADEC_Functions_C\t2hc_TMATS.c
