mex -g SSModelCFunc\FADEC_TJ1200.c...
    -g SSModelCFunc\TJ1200\FADEC_get_C\getTJ1200FADECContConst.c...
    -g SSModelCFunc\TJ1200\FADEC_get_C\getTJ1200FADECMtx.c      ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\getTJ1200FADECSizeConst.c...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200AMtx.c          ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200ASVec.c         ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200AltLinVec.c     ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200BMtx.c          ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200DSVec.c         ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200DeltaMtx.c      ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200FNcMaxContMtx.c ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200FNperContMtx.c  ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200MNLinVec.c      ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200N_KiMtx.c       ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200N_KishMtx.c     ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200N_KpMtx.c       ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200N_KpshMtx.c     ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200NcFANContMtx.c  ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200NcFANshContMtx.c...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200NcHPCMapMtx.c   ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200NcVec.c         ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200PRHPCMapMtx.c   ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200Pt3DMtx.c       ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200Pt3Mtx.c        ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200Pt5DMtx.c       ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200Pt5Mtx.c        ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200Ts0Mtx.c        ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200Tt4DMtx.c       ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200Tt4Mtx.c        ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200Tt5DMtx.c       ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200Tt5Mtx.c        ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200WcHPCMapMtx.c   ...
    -g SSModelCFunc\TJ1200\FADEC_get_C\Mtx\getTJ1200WfMtx.c         ...
    -g SSModelCFunc\FADEC_Functions_C\Ambient_TMATS.c    ...
    -g SSModelCFunc\FADEC_Functions_C\ControlFunctions.c ...
    -g SSModelCFunc\FADEC_Functions_C\FailSafeFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\MtxIntFunctions.c  ...
    -g SSModelCFunc\FADEC_Functions_C\PIMinMaxRF.c       ...
    -g SSModelCFunc\FADEC_Functions_C\PIOil.c            ...
    -g SSModelCFunc\FADEC_Functions_C\PcalcStat_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\PeripheralDyn.c    ...
    -g SSModelCFunc\FADEC_Functions_C\ShutDownFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\StartingFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\TCFault.c          ...
    -g SSModelCFunc\FADEC_Functions_C\functions_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\interp1Ac_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\interp2Ac_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\pt2sc_TMATS.c      ...
    -g SSModelCFunc\FADEC_Functions_C\sp2tc_TMATS.c      ...
    -g SSModelCFunc\FADEC_Functions_C\t2hc_TMATS.c
