mex -g SSModelCFunc\FADEC_GET700.c...
    -g SSModelCFunc\GET700\FADEC_get_C\getGET700FADECContConst.c...
    -g SSModelCFunc\GET700\FADEC_get_C\getGET700FADECMtx.c      ...
    -g SSModelCFunc\GET700\FADEC_get_C\getGET700FADECSizeConst.c...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700AMtx.c          ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700ASVec.c         ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700AltLinVec.c     ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700BMtx.c          ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700DSVec.c         ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700DeltaMtx.c      ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700FNcMaxContMtx.c ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700FNperContMtx.c  ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700MNLinVec.c      ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700N_KiMtx.c       ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700N_KishMtx.c     ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700N_KpMtx.c       ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700N_KpshMtx.c     ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700NcFANContMtx.c  ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700NcFANshContMtx.c...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700NcHPCMapMtx.c   ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700NcVec.c         ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700PRHPCMapMtx.c   ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700Pt3DMtx.c       ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700Pt3Mtx.c        ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700Pt5DMtx.c       ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700Pt5Mtx.c        ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700Ts0Mtx.c        ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700Tt4DMtx.c       ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700Tt4Mtx.c        ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700Tt5DMtx.c       ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700Tt5Mtx.c        ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700WcHPCMapMtx.c   ...
    -g SSModelCFunc\GET700\FADEC_get_C\Mtx\getGET700WfMtx.c         ...
    -g SSModelCFunc\FADEC_Functions_C\Ambient_TMATS.c    ...
    -g SSModelCFunc\FADEC_Functions_C\ControlFunctions.c ...
    -g SSModelCFunc\FADEC_Functions_C\FailSafeFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\MtxIntFunctions.c  ...
    -g SSModelCFunc\FADEC_Functions_C\PIMinMaxRF.c       ...
    -g SSModelCFunc\FADEC_Functions_C\PIOil.c            ...
    -g SSModelCFunc\FADEC_Functions_C\PcalcStat_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\PeripheralDyn.c    ...
    -g SSModelCFunc\FADEC_Functions_C\ShutDownFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\StartingFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\TCFault.c          ...
    -g SSModelCFunc\FADEC_Functions_C\functions_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\interp1Ac_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\interp2Ac_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\pt2sc_TMATS.c      ...
    -g SSModelCFunc\FADEC_Functions_C\sp2tc_TMATS.c      ...
    -g SSModelCFunc\FADEC_Functions_C\t2hc_TMATS.c
