mex -g SSModelCFunc\FADEC_TJ300AR.c...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\getTJ300ARFADECContConst.c...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\getTJ300ARFADECMtx.c      ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\getTJ300ARFADECSizeConst.c...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARAMtx.c          ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARASVec.c         ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARAltLinVec.c     ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARBMtx.c          ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARDSVec.c         ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARDeltaMtx.c      ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARFNcMaxContMtx.c ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARFNperContMtx.c  ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARMNLinVec.c      ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARN_KiMtx.c       ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARN_KishMtx.c     ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARN_KpMtx.c       ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARN_KpshMtx.c     ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARNcFANContMtx.c  ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARNcFANshContMtx.c...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARNcHPCMapMtx.c   ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARNcVec.c         ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARPRHPCMapMtx.c   ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARPt3DMtx.c       ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARPt3Mtx.c        ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARPt5DMtx.c       ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARPt5Mtx.c        ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARTs0Mtx.c        ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARTt4DMtx.c       ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARTt4Mtx.c        ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARTt5DMtx.c       ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARTt5Mtx.c        ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARWcHPCMapMtx.c   ...
    -g SSModelCFunc\TJ300AR\FADEC_get_C\Mtx\getTJ300ARWfMtx.c         ...
    -g SSModelCFunc\FADEC_Functions_C\Ambient_TMATS.c    ...
    -g SSModelCFunc\FADEC_Functions_C\ControlFunctions.c ...
    -g SSModelCFunc\FADEC_Functions_C\FailSafeFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\MtxIntFunctions.c  ...
    -g SSModelCFunc\FADEC_Functions_C\PIMinMaxRF.c       ...
    -g SSModelCFunc\FADEC_Functions_C\PIOil.c            ...
    -g SSModelCFunc\FADEC_Functions_C\PcalcStat_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\PeripheralDyn.c    ...
    -g SSModelCFunc\FADEC_Functions_C\ShutDownFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\StartingFunctions.c...
    -g SSModelCFunc\FADEC_Functions_C\TCFault.c          ...
    -g SSModelCFunc\FADEC_Functions_C\functions_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\interp1Ac_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\interp2Ac_TMATS.c  ...
    -g SSModelCFunc\FADEC_Functions_C\pt2sc_TMATS.c      ...
    -g SSModelCFunc\FADEC_Functions_C\sp2tc_TMATS.c      ...
    -g SSModelCFunc\FADEC_Functions_C\t2hc_TMATS.c
